# Generated by Django 3.2.16 on 2022-11-16 15:28

import clients.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientsPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=clients.models.clients_photo_path, verbose_name='Файл')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('born', models.DateField(verbose_name='Родился')),
                ('sex', models.CharField(choices=[('F', 'Женщина'), ('M', 'Мужчина')], max_length=1, verbose_name='Пол')),
                ('f_name', models.CharField(max_length=256, verbose_name='Имя')),
                ('l_name', models.CharField(max_length=256, verbose_name='Фамилия')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('photo', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='client', to='clients.clientsphoto', verbose_name='Фото')),
            ],
        ),
    ]
